### ISSUE TITLE
｢Suggestion] 建議收錄站酷的免費商用字體

### ISSUE THREAD

**Issue by only3km** [zenozeng/Free-Chinese-Fonts#12]
站酷高端黑 http://www.zcool.com.cn/special/gaoduanhei/
站酷快乐体  http://www.zcool.com.cn/special/happyfont/

**Comment by zenozeng** [comment]
@only3km 哇。谢谢。这两个字体都是可以免费商用？

**Comment by zenozeng** [comment]
@only3km 已添加。
