### ISSUE TITLE
Fandol字体 | Fandol fonts

### ISSUE THREAD

**Issue by dine2014** [zenozeng/Free-Chinese-Fonts#13]
这个列表应该把Fandol字体列进去吧。收字不多，但是是有宋、楷、黑、仿、粗宋、粗黑六种类型的简中字体，最重要的是：它是GPL授权。

http://ctan.org/pkg/fandol

**Comment by zenozeng** [comment]
@dine2014 你高兴发一个 Pull Request 吗？直接修改这个文件就好：https://github.com/zenozeng/Free-Chinese-Fonts/blob/master/src/fonts.json

**Comment by dine2014** [comment]
额，抱歉，不会用github也不会写json。

**Comment by zenozeng** [comment]
@dine2014 已合并到 json，十分感谢！
