### ISSUE TITLE
补充两点信息

### ISSUE THREAD

**Issue by Man-Ting-Fang** [zenozeng/Free-Chinese-Fonts#19]
一、
cwTeX 系列字体的官方下载地址是：
ftp://ftp.ntu.edu.tw/cwtex/util/TrueType/
另外我记得还有一两个网址，但似乎已失效，就算了。
cwTeX 的官方网址是：
http://homepage.ntu.edu.tw/~ntut019/cwtex/cwtex.html
从「下載 cwTeX 系統檔案」即可找到字体下载地址（上面已给出）。

二、
「刻石錄」网站上现有三种开源字体（网址附在后边）：I.明體、I.顏體、I.鋼筆鶴體，后两种是由王漢宗教授的字体修改而来，授权条款是 GNU GPL 2.0 或以上；I.明體则由日本 IPA 字型修改而来，授权条款是「IPA開放字型授權條款 第1.0版」（IPA Open Font License v1.0，IPAフォントライセンスv1.0）。以上三种字体的授权条款均可在相关页面上找到，字体下载压缩包里也包含了这些授权条款文本。

网址：
I.明體：http://founder.acgvlyric.org/iu/doku.php/造字:開源字型_i.明體
I.顏體：http://founder.acgvlyric.org/iu/doku.php/造字:開源字型_i.顏體
I.鋼筆鶴體：http://founder.acgvlyric.org/iu/doku.php/造字:開源字型_i.鋼筆鶴體
刻石錄网站首页：http://founder.acgvlyric.org/iu/doku.php/start
刻石錄之「造字」：http://founder.acgvlyric.org/iu/doku.php/造字:index

这三款字体是难得的开源旧字形字体，在下觉得质量较好，值得推荐。

**Comment by zenozeng** [comment]
@mtf-tpxs 
抱歉回得晚了，我原文收的字体不是 cwTeX 而是cwtex-q-fonts，其实是一个衍生版本。不过倒是确实应该补上 cwTeX 的官方网址。刻石錄字体确实很棒，我会添加上去，感谢推荐！

**Comment by zenozeng** [comment]
已更新。
