### ISSUE TITLE
书体坊的字体不知道是啥来头的？

### ISSUE THREAD

**Issue by illusate** [zenozeng/Free-Chinese-Fonts#27]
http://www.zhaozi.cn/html/fonts/china/shutifang/

**Comment by zenozeng** [comment]
查了一下官方的说法是：

> 我因为爱好书法，所以一直坚持做古代书法名家的字体。十多年来，在字体研究上付出了无数的心血和汗水。我为了生存，所以集古人书法所成的字体，要向用户适当的收取象征性的费用。喜欢者，请自觉付费使用。

参见：http://blog.sina.com.cn/s/blog_4e6ac4af0102wpqg.html
