### ISSUE TITLE
两个需要更正的地方

### ISSUE THREAD

**Issue by ShikiSuen** [zenozeng/Free-Chinese-Fonts#4]
首先，思源是基於SIL授权的；
其次，王汉宗字库当中已被确认无侵权嫌疑的字体有：
![image](https://cloud.githubusercontent.com/assets/3164826/8024544/93af5f48-0cf4-11e5-9752-360f0400989e.png)

**Comment by zenozeng** [comment]
恩，谢谢。确实 License 好像后来改了。我晚点更新下文档。

See also: https://github.com/adobe-fonts/source-han-sans/commits/master/LICENSE.txt

**Comment by zenozeng** [comment]
关于王汉宗字体的那个说明，有细节来源吗？

**Comment by ShikiSuen** [comment]
http://wiki.ubuntu.org.cn/index.php?title=%E5%85%8D%E8%B4%B9%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93

**Comment by zenozeng** [comment]
好的，谢谢，我晚点会更新加入这部分字体。
