### ISSUE TITLE
再加一坨

### ISSUE THREAD

**Issue by farteryhr** [zenozeng/Free-Chinese-Fonts#8]
官方：http://www39.atpages.jp/yagoinienie/851fontpage.html
简介：http://www.zhihu.com/question/20727176/answer/61080772
一个日本制、仍在更新的手写字体，覆盖绝大部分简体字，虽然某些字字形是日本的（有一些手写特征之后其实会弱化黑体宋体上的很多字形标准区别，如户言上的横），对中国人总的来说还是顺眼且好用。
补充：
王汉宗系列？
参考：http://wiki.ubuntu.com.cn/index.php?title=%E5%85%8D%E8%B4%B9%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93&variant=zh-cn
然后建议还是加点例图？
再补充
参考：http://wiki.debian.org.hk/w/Fonts

**Comment by zenozeng** [comment]
例图我倒是挺相加的，不过这个可能要好好考量一下版权问题。

**Comment by farteryhr** [comment]
于是这表列的都是免费字体吧，你这里展示程序也是开源的呀，应该犯不着任何一个版权了吧，岂不美哉（

**Comment by zenozeng** [comment]
fixed in https://github.com/zenozeng/Free-Chinese-Fonts/commit/7d284962bacc37caaefd09d314eacde47556eb40
